ICMSLST-2551 Add cache for django-compressor to use at build time.
This fixes the following bug:
CommandError: An error occurred during rendering
/code/web/templates/base.html: Missing connections string