Revert "ICMSLST-414 Use eventlet with gunicorn (#165)" (#176)
This reverts commit 64115f3098642b8afb979de576095b20272efbb2.

Reverts uktrade/icms#165
Error was 
redis.exceptions.ConnectionError: Error -3 connecting to redis:6379. Lookup timed out

Related problem: https://github.com/celery/celery/issues/5924